sudo: required
dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - valgrind
      - libstdc++-5-dev  # default version is not valgrind-clean

# test_layers takes a long time; divide up the work into multiple jobs on the
# matrix so we don't time out on Travis
matrix:
  include:
    - env: COMMAND=./test_layers
    - env: COMMAND=./test_apps

script:
  - $COMMAND $START $END

notifications:
  email:
    on_success: never
    on_failure: always
