sudo: required
dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - valgrind
      - libstdc++-5-dev  # default version is not valgrind-clean

matrix:
  include:
    - env: COMMAND=./test_layers
    - env: COMMAND=./test_apps

script:
  - $COMMAND

notifications:
  email:
    on_success: never
    on_failure: always
